stages:
- stage: Compile
  jobs:
  - job: Compile
    container: gradle:7.1-jdk8
    steps:
    - script: chmod +x gradlew && ./gradlew build jacocoTestReport
    - script: ls 
# - stage: SonarQube
#   jobs:
#   - job: Sonarscan
#     steps:
#     - script: |
#         echo "Sonarqube Integration"
# - stage: DockerBuildPush
#   jobs:
#   - job: DockerBuildPush
#     steps:
#     - script: |
#         echo "Docker Build"
#         echo "Docker Push"